### ISSUE TITLE
Rally community...

### ISSUE THREAD

**Issue by EmergentBehavior** [graphql-go/graphql#29]
Browsing around it looks like the go-graphql landscape is still in its infancy, however `graphql-go` seems to be one of the more referenced libs out there. I'm looking at using it in my own work and would potentially be happy to start contributing, but it would be helpful to sketch out some a bit more detailed roadmap and near-term goals so potential contributors can see what to focus on.

**Comment by pyros2097** [comment]
Yeah... We started using it too.. some contributor guidelines will help and maybe some Todos and features complete w.r.t. graphql-js would be good

**Comment by EcutDavid** [comment]
+1

**Comment by sogko** [comment]
Thanks @EmergentBehavior for bringing this up 👍🏻

You are right that this area is lacking and requires more attention. (Previously I relied on the TODO list on the README to see how I can contribute but I noticed it's out-of-date currently.)

I can help out with sharing the latest nearest-of-the-nearest-term goals that we definitely need to address
- [ ] Package renaming and reorganisation
  - Discussed in PR #20 and PR #16 
  - Currently being attempted in PR #30 

Other longer-term goals
- [x] Lexer
- [x] Parser
- [x] Schema Parser
- [x] Printer
- [x] Schema Printer
- [x] Visitor
- [x] Executor
- [ ] Validator (optional according to specs, but nice to have)
- [ ] Basic usage / examples
  - Related PR #21 (first example)
- [ ] Relay/React example (though I've started to write a [couple of posts on Medium](https://wehavefaces.net) touching this topic)
- [ ] Release v0.1

As to the parity of this project vs `graphql-js`, it was ported from v0.4.3 of `graphql-js` (July 2015 spec, excluding `validator`) (specifically commit [e556526](https://github.com/graphql/graphql-js/commit/e556526313909b409821098283f52838a99d3f48) ). It's currently behind (latest v0.4.12) but once the package name has been resolved and stable, it'll be easier to get back on track. 

But I doubt it'll be a 1-1 port with `graphql-js` from there on, we'd have to go by [the GraphQL spec releases](https://github.com/facebook/graphql/releases) instead. In other words, we'd have to base our implementation based on October 2015 spec next.

Cheers!

**Comment by bbuck** [comment]
@sogko For information on unimplemented features as of yet (such as the Validator) is the single source of truth just the spec for GraphQL or do you already have plans you'd like to see done specifically for those features? I'd love to help contribute and just want to make sure that I don't do a lot of work on something in a way different from the plans of this library moving forward.

Also, I know you do a lot of work with this library outside of just this, such as your graphql-go-handler and your Relay specific wrapper for this library. Which are all great things. One thing I found lacking was specifically related to this library (as addressed in the 'Documenation' issue) is to have more examples specifically focusing on basic usage of just this library.

I spent some time with graphql-js after finding graphql-go to define the things I was looking to define before finally coming back here and having the ability to transfer that knowledge into how to do those similar things in Go. Which is great that this could be done, but any examples that get written (including yours), I think would be extremely beneficial if they only used this library to handle the GraphQL pieces. Even if you define it all raw with GraphQL as is and then _refactor_ it using your Relay wrapper for example so at least the understanding of this library is talked about and discussed. 

I'm bringing this up not just because of my desire to have seen that but a recent conversation in Gitter (for this repo). I'm referring to this comment from *thanhliem89dn* specifically (and I share his sentiment, this was my desire as well): 

> I'm reading todo example from [sogko] https://github.com/sogko/todomvc-relay-go/blob/master/data/schema.go but He used gqlrelay and I just want to use graphql at all

All of these utilities are great to have, but I think a full understanding of this library offers is a better place to start before introducing the other ones.

I got off topic and rambled. I'm sorry.

**Comment by EmergentBehavior** [comment]
@sogko Thanks for the update. Am going to submit another PR to update the `README` with this information.

**Comment by sogko** [comment]
@EmergentBehavior that's excellent 👍🏻! Thanks!

**Comment by EmergentBehavior** [comment]
Submitted! https://github.com/chris-ramon/graphql-go/pull/32

**Comment by sogko** [comment]
@bbuck Thanks for the input, appreciate very much 👍🏻

Yes you are right, documentation is really lacking right now, in this project and others in its ecosystem currently. I think once we nail down the package naming, I'll help and do my part in providing better documentation.

I wrote the `graphql-relay-go` and `graphql-go-handler` libraries because I was being impatient and wanted to quickly have some form of Relay-compliant server for golang that can actually run lol. I realised that besides `graphql-go`, there were bits and pieces missing to get it (i.e. Relay-compliant server) to work.

I have yet to put down my motivations on why I wrote those, but to draw parallels with the GraphQL in JS:
- [`graphql-go`](https://github.com/chris-ramon/graphql-go) == [`graphql-js`](https://github.com/graphql/graphql-js)
Server-side implementation of graphql
- [`graphql-go-handler`](https://github.com/sogko/graphql-go-handler) == [`express-graphql`](https://github.com/graphql/express-graphql)
Middleware to handle GraphQL queries through HTTP requests. It parses GET/POST params and passes them into Graphql(), which returns JSON response. 
You can choose not to use it, but you will end up writing similar code. As to whether it should be merged with `graphql-go`, I think it could possibly be. Or it could remain separate, just like `express-graphql`.
Either way, I'm open to merging it based on the community's decision.
- [`graphql-relay-go`](https://github.com/sogko/graphql-relay-go) == [`graphql-relay-js`](https://github.com/graphql/graphql-relay-js)
This is a library to construct Relay-compliant servers, which has additional specs for pagination, global IDs and those sort of things. Not needed if you chose to build a pure GraphQL server.

Some of the other projects that I contributed do use `graphql-go` + `graphql-go-handler` + `graphql-relay-go`, but they are specifically Relay applications:
- [`golang-relay-starter-kit`](https://github.com/sogko/golang-relay-starter-kit)
- [`todomvc-relay-go`](https://github.com/sogko/todomvc-relay-go)

Another project that I wrote used only  `graphql-go` + `graphql-go-handler`, with `graphiql` for the front-end:
- [`golang-graphql-playground`](https://github.com/sogko/golang-graphql-playground) (Query only example, no mutations)

I did wrote a couple of posts [on Golang + GraphQL + Relay](http://wehavefaces.net) but again, those are heading into the direction of Relay-specific details.

I do see what you mean there about diving deeper into examples pure GraphQL using `graphql-go`. Better and in-depth examples on 
- how to define schemas, 
- probably touches as many GraphQL types as possible
- especially mutations
We definitely could use with those. 
Let's see what we could do.

Thanks again! Cheers!

**Comment by pyros2097** [comment]
Most of the vital info seems to be shared in these issues I'm gonna be putting them in the Readme

**Comment by EmergentBehavior** [comment]
Not critically important, but now that the package and its sister packages are collected under `graphql-go`, perhaps we should give the project a logo :). How about this?

![graphqlgo](https://cloud.githubusercontent.com/assets/3324637/10973818/13f5634e-83ad-11e5-864e-32fcfbd9bddb.png)

**Comment by sogko** [comment]
The gopher strikes again haha! Thanks @EmergentBehavior for kicking this off! 
Yeah, we definitely a logo for our community 👍🏻

For inspirations from other implementations:
- [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) (Ruby)
![](https://cloud.githubusercontent.com/assets/2231765/9094460/cb43861e-3b66-11e5-9fbf-71066ff3ab13.png)

- [graphene](https://github.com/graphql-python/graphene) (Python, and their website is pretty impressive http://graphene-python.org)
![](https://camo.githubusercontent.com/04f2156e9ca5d92073997410a3ee3f379c584e20/687474703a2f2f6772617068656e652d707974686f6e2e6f72672f66617669636f6e2e706e67)

- [sangria](https://github.com/sangria-graphql/sangria) (Scala)
![](https://raw.githubusercontent.com/sangria-graphql/sangria-logo/master/sangria-logo.png)

**Comment by EmergentBehavior** [comment]
graphql-ruby and graphene ones are great. i can help with a front-end website later too once package is a little more stable. Ruby and Python have more elegant base logos though so it's easier to iterate :)

**Comment by omgj** [comment]
Any updates regarding documentation? I'm reading through the source code and there are comments here and there but I think its not as clear as it could be.

Also, the reference spec is at April 2016, not October 2015 which it says in README.md

And just a thought for the logo - The python logo looks almost like a G, make it a G. and add an o afterwards.

**Comment by kmulvey** [comment]
Keep the dream alive

cc: @logie17

**Comment by chris-ramon** [comment]
Thanks a lot guys :star2: for taking the time to bring interesting ideas, since https://github.com/graphql-go/graphql/pull/32 was merged; let's close this one issue; and continue the conversation on:
- Gitter: https://gitter.im/graphql-go/graphql
- Slack: https://graphql.slack.com/messages/C07NEH9EU
